name: Bikin APK Flutter + Rust

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # PERBAIKAN DI SINI: Ganti 3.24.0 jadi 3.24.4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4' 
          channel: 'stable'

      - name: Setup Rust & Android Targets
        run: |
          rustup toolchain install stable
          rustup target add aarch64-linux-android armv7-linux-androideabi x86_64-linux-android

      - name: Install Flutter Rust Bridge Codegen
        run: cargo install flutter_rust_bridge_codegen

      - name: Generate Bridge Code
        run: flutter_rust_bridge_codegen generate

      - run: flutter pub get

      - run: flutter build apk --debug

      - uses: actions/upload-artifact@v4
        with:
          name: aplikasi-rust-sakti
          path: build/app/outputs/flutter-apk/app-debug.apk